---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp-ingressroute
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`headlamp.cluster.zolli-home.hu`)
      priority: 10
      services:
        - name: headlamp
          port: 80
          scheme: http
  tls:
    secretName: wildcard-cluster-zolli-home-hu-tls
