---
apiVersion: v1
kind: Service
metadata:
  name: onepassword-connect
  namespace: onepassword-connect
  labels:
    app.kubernetes.io/name: onepassword-connect
    app.kubernetes.io/component: connect-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: onepassword-connect
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  sessionAffinity: ClientIP
