apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - namespace.yaml
  - externalsecret.yaml
  - clusterissuer-staging.yaml
  - clusterissuer-production.yaml
  - certificate-wildcard.yaml
  - certificate-internal-ca-root.yaml
  - clusterissuer-internal-ca.yaml
